name: docker-spa
description: This GitHub Action will build your vite app and turn it into a docker container
author: johnb8005
branding:
  icon: book-open
  color: purple
inputs:
  githubtoken:
    description: github token
    default: ${{ github.token }}
  port:
    description: docker port token
    default: 3000
  distFolder:
    description: path to dist/build folder
    default: dist
  nodeversion:
    description: node version
    default: 18
  html-entry:
    description: HTML entry point
    default: index.html
  container-name:
    description: name of the container
    default: ${{ github.event.repository.name }}
  build-command:
    description: build command
    default: VITE_VERSION=${GITHUB_REF##*/} VITE_GIT_SHA=$GITHUB_SHA yarn build
  message:
    description: The message to prepend the review suggestion
  dockerhub-url:
    description: DockerHub URL
    required: false
runs:
  using: "composite"
  steps:
    - uses: nexys-system/gh-actions-spa-test@v1.0.2
      with:
        nodeversion: ${{ inputs.nodeversion }}
        build-command: ${{ inputs.build-command }}
    - name: Gzip
      run: gzip -r -k ${{ inputs.distFolder }}
      shell: bash
    - name: Create httpd.conf (required for Docker)
      run: echo "E404:${{ inputs.html-entry }}" > httpd.conf
      shell: bash
    - name: Create meta json file
      run: printf "{\"sha\":\"$GITHUB_SHA\",\"version\":\"${GITHUB_REF##*/}\",\"date\":\"$(date -u)\"}" > meta.json
      shell: bash
    - name: Create docker file
      run: printf "FROM lipanski/docker-static-website:2.1.0\nCOPY httpd.conf .\nCOPY ${{ inputs.distFolder }} .\nCOPY meta.json .\nCMD [\"/busybox\", \"httpd\", \"-f\", \"-v\", \"-p\", \"${{ inputs.port }}\", \"-c\", \"httpd.conf\"]" > Dockerfile
      shell: bash
    - name: Set env var
      run: |
        if [ -z "${{ inputs.dockerhub-url }}" ]; then
          echo "DOCKERHUB_URL=ghcr.io/${GITHUB_REPOSITORY,,}/${{ inputs.container-name }}" >> $GITHUB_ENV
        else
          echo "DOCKERHUB_URL=${{ inputs.dockerhub-url }}" >> $GITHUB_ENV
        fi
      shell: bash
    - name: Login to DockerHub Registry
      run: echo "${{ inputs.githubtoken }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      shell: bash
    - name: Create docker container
      run: docker build --tag $DOCKERHUB_URL:latest --tag $DOCKERHUB_URL:master --tag $DOCKERHUB_URL:${GITHUB_REF##*/} .
      shell: bash
    - name: Push Docker
      run: docker push --all-tags $DOCKERHUB_URL
      shell: bash
  
